ENTRY(_start) /*Entry point sympol of the binaries compiled*/
SECTIONS {
    . = 2M; /* Safe value for BIOS/UEFI to load kernel into*/

    .text BLOCK(4K) : ALIGN(4K) {
        *(.multiboot)
        *(.text)
    }

    .rodata BLOCK(4K) : ALIGN(4K) {
        *(.rodata)
    }

    .data BLOCK(4K) : ALIGN(4K) {
        *(.data)
    }

    .bss BLOCK(4K) : ALIGN(4K) {
        *(COMMON)
        *(.bss)
    }

}